<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="first.css" type="text/css"?>
<!DOCTYPE animals[
<!ELEMENT animals (head, animal, animal, animal, animal)>
<!ELEMENT head (nkind_of_animal, ndescription)>
<!ELEMENT nkind_of_animal (#PCDATA)>
<!ELEMENT ndescription (#PCDATA)>
<!ELEMENT animal (kind_of_animal, description)>
<!ELEMENT kind_of_animal (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ENTITY bear "Медведь">
<!ENTITY fox "Лиса">
<!ENTITY wolf "Волк">
<!ENTITY hare "Заяц">
]>
<animals>
    <head>
        <nkind_of_animal>Вид животного</nkind_of_animal>
        <ndescription>Описание животного</ndescription>
    </head>
    <animal>
        <kind_of_animal>&bear;</kind_of_animal>
        <description>
            &bear; – самый крупный хищник на земле. Это животное относится к классу млекопитающие, отряду хищные, семейству медвежьи, роду медведи (Ursus). &bear; появился на планете около 6 млн. лет назад и всегда был символом мощи и силы. 
            В зависимости от видовой принадлежности длина тела хищника может колебаться от 1,2 до 3 метров, а вес медведя варьируется от 40 кг до тонны. Тело у этих животных крупное, коренастое, с толстой, короткой шеей и большой головой. Мощные челюсти позволяют легко разгрызать как растительную, так и мясную пищу. Конечности довольно короткие и слегка изогнуты. Поэтому медведь ходит, покачиваясь из стороны в сторону, и опирается на всю ступню. Скорость медведя в моменты опасности может достигать 50 км/ч. При помощи больших и острых когтей эти животные добывают из-под земли пищу, разрывают добычу и вскарабкиваются на деревья. Многие виды медведей хорошо плавают. У белого медведя для этого между пальцами есть специальная перепонка. Продолжительность жизни медведя может достигать 45 лет.
            Медведи не отличаются острым зрением и хорошо развитым слухом. Это компенсируется великолепным обонянием. Иногда животные встают на задние лапы, чтобы при помощи нюха получить информацию об окружающей обстановке.
            Густая шерсть медведя, покрывающая тело, имеет различный окрас: от рыжевато-коричневого до черного цвета, белого у полярных медведей или черно-белого у панд. Виды с темным мехом к старости седеют и становятся серыми.
            В рацион медведя входит как растительная, так и животная пища. Бурые медведи кроме ягод, грибов, орехов и различных корешков едят мясо оленей, косуль или лосей. Не откажутся они и от рыбы. Зверь может полакомиться муравьями, личинками и медом диких пчел. Панда питается исключительно побегами молодого бамбука, а гималайский медведь, кроме растительной пищи, ест лягушек, насекомых и моллюсков. Белые медведи являются настоящими хищниками, поэтому растительным рационом их не удивить.
        </description>
    </animal>
    <animal>
        <kind_of_animal>&fox;</kind_of_animal>
        <description>
            &fox; (лисица) (Vulpes) – это хищное млекопитающее, относится к отряду хищные, семейству псовые. Латинское название рода лисицы, по всей видимости, произошло от искаженных слов: латинского «lupus» и немецкого «Wolf», переводящихся как «волк». В старославянском языке прилагательному «лисый» соответствовало определение желтоватого, рыжего и желтовато-оранжевого цвета, характерного для окраса широко распространенной лисы обыкновенной.
            В зависимости от видовой принадлежности размеры лисы варьируются от 18 см (у фенека) до 90 см, а вес лисы колеблется от 0,7 кг (у фенека) до 10 кг. Лисицы имеют характерный родовой признак – стройное удлиненное туловище с довольно короткими конечностями, слегка вытянутую морду и хвост.
            Пушистый хвост лисицы служит своеобразным стабилизатором во время бега, а в зимние холода используется для дополнительной защиты от морозов.
            Длина хвоста лисы зависит от вида. У фенека она достигает 20-30 см. Длина хвоста лисицы обыкновенной равна 40-60 см.
            Лисы больше полагаются на осязание и обоняние, чем на зрение. Они обладают чувствительным нюхом и отменным слухом.
            Уши у них довольно крупные, треугольные, чуть вытянутой формы, с острой вершинкой. Самые большие уши у фенека (до 15 см в высоту) и большеухой лисицы (до 13 см в высоту).
            Зрение животных, адаптированное для ночного образа жизни, позволяет представителям рода прекрасно реагировать на движение, однако строение глаза лисицы с вертикальными зрачками не приспособлено для распознавания цветов.
            Всего у лисы 42 зуба, кроме большеухой лисицы, у которой вырастает 48 зубов.
            Густота и длина волосяного покрова этих хищников зависит от времени года и климатических условий. В зимнее время и в районах с суровыми погодными условиями мех лисы становится густым и пышным, летом пышность и длина шерсти уменьшается.
            Цвет лисы может быть песочным, рыжим, желтоватым, бурым с отметинами черного или белого цвета. У некоторых видов цвет меха может быть практически белым или черно-бурым. В северных широтах лисы более крупные и имеют более светлый окрас, в южных странах окрас лисицы более тусклый, а размеры животного более мелкие.
            При преследовании жертвы или в случае опасности лиса способна развивать скорость до 50 км/ч. Во время брачного периода лисы могут издавать лающие звуки.
            Продолжительность жизни лисицы в естественных условиях колеблется от 3 до 10 лет, однако в неволе лиса живет и до 25-ти летнего возраста.
        </description>
    </animal>
    <animal>
        <kind_of_animal>&wolf;</kind_of_animal>
        <description>
            &wolf; — это хищное млекопитающее, которое относится к отряду хищные, семейству псовые (собачьи, волчьи).
            Русское слово “&wolf;” созвучно с некоторыми славянскими названиями зверя: болгары называют хищника вылк, сербы — вук, украинцы — вовк. Происхождение названия восходит к старославянскому слову “вылкъ”, означавшему таскать, уволакивать.
            Большинство волков — хищники среднего и большого размера, наиболее крупными являются серый и полярный волки: их рост в холке может достигать 85 см, а длина туловища без учета хвоста составляет 150-160 см. Размер и вес хищников полностью соответствуют правилу Бергмана: чем суровее среда обитания — тем крупнее зверь, поэтому самые большие волки весом до 85-90 кг обитают в Сибири, хотя средняя масса волка составляет около 35-50 кг. Самые мелкие — это аравийские волки, их максимальный рост в холке составляет всего 66 см, а вес самок не превышает 10 кг. У любой разновидности волков самки мельче самцов.
            Внешне волки похожи на больших собак с сильным, мускулистым телом и высокими ногами, только гривистые волки больше напоминают длинноногих лисиц, а красные волки обладают особенностями волков, лисиц и шакалов.
            У хищников длинный и толстый хвост, который у некоторых видов вырастает до 56 см в длину и всегда опущен вниз. Голова волка массивная, с высоко поставленными острыми ушами, а морда удлиненная и широкая. Череп красного и гривистого волков по форме напоминает лисий.
            Волчья пасть вооружена 42 зубами: хищные зубы предназначены для разрывания добычи на куски и перемалывания костей, а с помощью клыков зверь крепко держит и тащит свою жертву.
            Только у красных волков зубная формула содержит меньшее количество коренных зубов.
            Волчата появляются на свет с голубыми глазами, но уже к третьему месяцу радужина приобретает оранжевый или золотисто-желтый цвет, хотя встречаются волки, которые всю жизнь остаются голубоглазыми.
            Мех волка густой и двухслойный: подшерсток образован водонепроницаемым пухом, а верхний слой составляют остевые волосы, отталкивающие грязь и влагу. Низкая теплопроводность шерсти позволяет животным выживать в самых суровых климатических условиях.
            Окрас волков отличается богатым спектром оттенков, включающим различные вариации серого, белого, черного и коричневого цветов, хотя нередко мех бывает рыжим, чисто белым или практически черным. Считается, что окрас шерсти позволяет хищникам гармонично сливаться с окружающим ландшафтом, а смешение различных оттенков подчеркивают индивидуальность животных.
            Волки — пальцеходящие животные: опора на пальцы позволяет им балансировать свой вес во время передвижения. Сильные конечности, узкая грудина и покатая спина позволяют хищникам преодолевать значительные расстояния в поисках пищи. Обычный аллюр волка — легкий бег рысью со скоростью около 10 км/ч. Скорость волка, преследующего добычу, может достигать 65 км/ч.
            У волка прекрасный слух, зрение гораздо слабее, зато обоняние развито превосходно: хищник чует добычу за 3 км, а способность различать несколько миллионов различных оттенков запаха имеет большое значение в период гона, во время охоты и при коммуникативном общении животных. Мочевые и фекальные метки используются для обозначения границ территории.
            Голосовой диапазон волков богат и разнообразен: хищники воют, ворчат, тяфкают, визжат, рычат, хныкают и передают голосом сложные сообщения другим членам стаи. На рассвете можно услышать “хоровое пение” волков. Считается, что волки воют на луну, но на самом деле воем животные сообщают членам стаи о своем местонахождении и отгоняют чужаков. Одиночные животные, которые обитают вне стаи, редко воют, чтобы не навлечь на себя беду.
            Мимика волков также очень сильно развита: благодаря положению рта, губ, ушей и хвоста, а также показу зубов хищники выражают свое эмоциональное состояние. Как и у домашней собаки, поднятый хвост и уши волка означают настороженность или агрессию.
            Волки — одни из самых ловких, быстрых и выносливых хищников, выслеживающих и без устали преследующих свою добычу. Рацион волка зависит от доступности кормов и у большинства разновидностей состоит преимущественно из животной пищи. Волки одинаково успешно охотятся стаей и поодиночке, но загнать и атаковать крупную добычу, например, северного оленя, зубра или яка могут только сплоченной охотой. В 60% случаев волки нападают на молодых, старых, больных или раненых животных, при этом они отлично чувствуют, является ли животное сильным и здоровым или болезненным и ослабленным.
            В дикой природе &wolf; питается крупными животными (лоси, олени, косули, сайгаки, антилопы, бизоны, кабаны), более мелкими млекопитающими (зайцы, суслики, бобры, броненосцы, мыши, лемминги), а также рыбой, птицами, насиживающими кладку, и их яйцами. Добычей волков часто становятся крупные и мелкие домашние животные и птицы (гуси, утки, овцы, коровы, лошади), а также лисы, дикие собаки и корсаки.
            При отсутствии основного источника питания волки не гнушаются мелкими земноводными (например, лягушками), ящерицами, насекомыми (жуками, саранчой) и падалью (например, мертвыми тюленями, выброшенными на берег). В теплое время года в рационе хищников появляются ягоды, грибы и спелые плоды.
            В степях волки утоляют жажду на полях с бахчевыми культурами – арбузами и дынями. Голодные хищники даже нападают на медведей в спячке, не упустят случая разорвать ослабленное и больное животное, съедая за раз до 10-14 кг мяса. Изголодавшийся полярный волк съедает зайца-беляка целиком, с костями и шкурой. Интересной особенностью волков считается их привычка возвращаться к трупам недоеденной жертвы, а также прятать излишки мяса про запас.
        </description>
    </animal>
     <animal>
        <kind_of_animal>&hare;</kind_of_animal>
        <description>
            &hare; – животное, которое относится к классу млекопитающие, отряду зайцеобразные, семейству зайцевые, роду зайцы (Lepus). Вопреки бытующему мнению они не относятся к грызунам и далеко не так безобидны. В случае опасности они проявляют агрессивность и оказывают сопротивление нападающему. С древних времен заяц является желанным трофеем для охотников из-за вкусного мяса и теплого меха.
            Тело зайца стройное, немного сжатое с боков, его длина у некоторых видов достигает 68-70 см. Вес зайца может превышать 7 кг. Характерной чертой зайцеобразных являются клиновидные уши, достигающие в длину от 9 до 15 см. Благодаря ушам слух зайца развит намного лучше, чем обоняние и зрение. Задние конечности у этих млекопитающих имеют длинные ступни и развиты сильнее передних. При возникновении угрозы скорость зайца может достигать 80 км/ч. А способность внезапно изменять направление бега и резко прыгать в сторону позволяет этим животным избавиться от преследования врагов: волка, лисицы, совы и т.д. Зайцы хорошо бегают вверх по склонам, но вниз приходится спускаться кубарем.
            Цвет зайца зависит от сезона. Летом мех животного имеет рыжевато-серый, бурый или коричневый оттенок. Из-за темного цвета подшерстка окрас получается неравномерный с крупными и мелкими «пестринами». Мех на животе белого цвета. Зайцы меняют окраску зимой, их мех светлеет, но полностью белоснежным становится только заяц-беляк. Кончики ушей у всех представителей рода остаются черными круглый год.
            Средняя продолжительность жизни самцов не превышает 5 лет, самок – 9 лет, однако есть зафиксированные случаи более длительного срока жизни зайца – около 12-14 лет.
            В рацион зайцев в весеннее и летнее время входят молодые ветви и побеги кустарников и деревьев, листья различных растений, клевер, одуванчик и другие травы. Не откажутся они от овощных и бахчевых культур.
            Зимой зайцам приходится выкапывать из-под снега остатки сельскохозяйственных культур, питаться корой кустарников и деревьев, в том числе плодовых, нанося им вред. В северных районах отмечены случаи, когда зайцы съедали куропаток, попавших в охотничьи силки. Поэтому чистыми вегетарианцами зайцев не назовешь.
        </description>
    </animal>
</animals>